### ISSUE TITLE
[Desktop] Enable developer tools on production release

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#2023]
Currently you can't right click to inspect element, which would be really helpful while trying to build svg and html outputs.

**Comment by rgbkrk** [comment]
We so need this still. 😏

**Comment by willingc** [comment]
@rgbkrk Is this resolved with the menu toggle for developer tools?

**Comment by rgbkrk** [comment]
I think only in dev mode, not in prod mode (for desktop).

**Comment by kelleyblackmore** [comment]
I was actually thinking about making a project board for upgrading the desktop app so I can track all the issues and features

**Comment by rgbkrk** [comment]
I'm in support of folks stewarding the next desktop release milestone. ❤️

**Comment by captainsafia** [comment]
I think we can close this now. Developer tool are available via the menu on the main releases of the Mac and Windows app.

You still can't right click to inspect element but I think having Developer Tools enabled via a menu item is enough to resolve this issue.
