### ISSUE TITLE
autocomplete with Julia

### ISSUE THREAD

**Issue by PaulSoderlind** [nteract/archived-desktop-app#4415]
in nteract 0.14.2 (on Windows 10), using the Julia 1.1.1 kernel there seems to be no auto-complete. 

To reproduce:
type `ab` and nothing happens (with/without Ctrl-Space).

In contrast, with the python3 kernel, it works.

**Comment by BenRussert** [comment]
I tried debugging this for a bit and didn't find a fix yet. The Julia inspection and completion messaging works in hydrogen with the same kernel so I think the issue is somewhere in the monorepo.

If I subscribe to the kernel observable in the console and log all the kernel messages in nteract I don't see any complete or inspect replies coming through. I do see a time out error message for completion requests.

My guess is we are mistakenly filtering out messages for some reason. The timeout limit seems to be much longer than even a slow reply would take so I don't think thats the issue.

**Comment by captainsafia** [comment]
@BenRussert Is this issue resolved now that #4453 is in?

**Comment by BenRussert** [comment]
@captainsafia unfortunately not. Both inspection and completion are not working. It seems to me that the inspection request messages sent to IJulia are ignored silently.

My guess was it's something about the format of the inspect_request message, but took a pretty close look and found no issues. Inspection works fine on hydrogen, but I'm not sure what we do differently. I was thinking of asking for debug suggestions on the IJulia repo next.

I'm really curious about this one, so let me know if you have debug suggestions or slack me if you want to pair up sometime.

**Comment by captainsafia** [comment]
@BenRussert Got it! Thanks for clarifying. I'd be interested in helping out. I'll ping you on Slack to discuss more.

**Comment by padmer** [comment]
I tried with Julia v1.2.0 and nteract 0.15.0 and still get the same issue. After Ctrl-. or Ctrl-Space it shows busy on the bottom left for some seconds then goes back to idle but autocomplete doesn't work for me.

**Comment by willingc** [comment]
Closing and consolidating autocomplete under #4995
