### ISSUE TITLE
Inline plot scroll

### ISSUE THREAD

**Issue by y-chachan** [nteract/archived-desktop-app#5131]
I suspect this is an elementary problem that has an easy solution but my nteract desktop notebooks moved from showing complete plots to incorporating a rather unwelcome scroll bar that needs to be used for me to see the entirety of the plot or different plots produced by the same cell. As far as I know, I have not changed any start up settings that led to this change. Please let me know how I can fix this problem, thanks!

**Comment by captainsafia** [comment]
Hello @y-chachan!

By default, outputs are considered collapsed in the nteract desktop app. For the past few months, we had a bug where the collapsed outputs were not rendered correctly causing all outputs to be expanded.

We fixed this bug in the latest release which is why you are seeing this issue. To resolve this, you can try going to the cell menu (the down error next to the play button) and expanding the cell output.

**Comment by y-chachan** [comment]
Hello @captainsafia, thank you for your prompt response. That was the first thing I tried because I figured I might have changed the settings. But somehow, toggling the expanded output option does not have the desired effect. The plots still appear with a scroll bar.

**Comment by captainsafia** [comment]
Thanks @y-chachan! We've fixed this issue in #5133 and it will ship as part of the June release.

**Comment by neumannrf** [comment]
@captainsafia Is there a way for me to enable Expanded Output as the default? Or do I have to toggle it for every single output window, one at a time?

**Comment by captainsafia** [comment]
You will have to toggle it.

If you're interested in submitting a contribution to make it configurable, it would be welcome!
