### ISSUE TITLE
nteract desktop hangs on launch

### ISSUE THREAD

**Issue by chameroy** [nteract/archived-desktop-app#5190]
I just installed nteract desktop 0.24 on Windows 10 (2004) and the application seems to hang during launch, never proceeding past the splash screen.

**Comment by chameroy** [comment]
It now works. I had originally uninstalled 0.23.3 prior to installing 0.24. When I couldn't get 0.24 to start up, I uninstalled 0.24 and reinstalled 0.23.3. However, when I then ran 0.23.3, it automatically updated to 0.24. After that, 0.24 now starts.

**Comment by chameroy** [comment]
I'm also encountering the startup issue on MacOS 10.15.5. However, unlike with Windows, going the update route does not get me around the issue.

**Comment by ctakasaka** [comment]
> 
> 
> I'm also encountering the startup issue on MacOS 10.15.5. However, unlike with Windows, going the update route does not get me around the issue.

Although I'm on Windows, this may work for you. I just had to select the nteract icon in my menu bar and forced it to open a new notebook with some engine. Then I could use nteract normally since the window then appeared. I think you could find something similar in your menu bar up top.

**Comment by chameroy** [comment]
Yes, it did! Even while the loading screen is still showing, the top bar menus are already available and I could use the file menu to create a new window.

Thanks. At least there's a workaround for both platforms for right now.

For the developers: would it be possible to not force updates in case a new release isn't working properly? In both of my cases, I tried to downgrade to 0.23.3, but was then forced to update to the new version.

**Comment by chameroy** [comment]
Also, clicking on a notebook file in macOS also successfully starts up the application. I don't know about Windows. I guess the only issue might be that the application does not start up with a new window.

**Comment by ichit** [comment]
I am on windows 10. Version 0.24 works  perfectly  well, and i must confess it has a cool GUI. Thanks developers. You guys are doing great work .

**Comment by captainsafia** [comment]
> For the developers: would it be possible to not force updates in case a new release isn't working properly? In both of my cases, I tried to downgrade to 0.23.3, but was then forced to update to the new version.

You can disable auto-updates by setting the `NTERACT_DESKTOP_DISABLE_AUTO_UPDATE` environment variable to "1".

I'm not sure why you're experiencing inconsistent behavior with launching.

If you'd like to help us debug the issue further, you can try to see if you can reproduce the issue when running a development instance of nteract by cloning the repository and building the application from the source.

That'll help identify what hiccups occur during the initialization that prevent the app from starting.

**Comment by neolee** [comment]
Same here. I wonder why it's not labelled as bug by devs. It's obvious and easy to re-produce (on both Windows and macOS).

**Comment by captainsafia** [comment]
I was just able to reproduce this on a Windows VM while validating another issue. This doesn't reproduce on my macOS dev machine.

Considering this and the fact that we haven't had an excessive amount of bug reports for this (compared to monthly users for nteract), there is something funkier going on here.

Now that I have a repro, I can dig around to see what might be going on.

**Comment by matesitox** [comment]
Same issue on ubuntu 2020.4 where I installed nteract 0.24.0 as a snap. nteract never gets past the splash screen.

**Comment by sammdu** [comment]
Same on Ubuntu 18.04, nteract v0.24.0

It only opens existing notebooks, but cannot seem create a new notebook upon launch, therefore stuck at splash screen.

This wasn't an issue in nteract v0.23.x

**Comment by axidio** [comment]
I have two macs. nteract starts normally on one. On the other mac, the splash screen will persist. Both macs are running up-to-date macOS.

**Comment by captainsafia** [comment]
@CrystallineCat I looked through a list of the commits that we published between v0.23.3 and v0.24.0. The config changes were the only major changes that happened in our startup flow. Is there anything there that you think might be sporadically causing hangs on startup?

**Comment by CrystallineCat** [comment]
@captainsafia I looked through the code, and I downloaded the v.0.24.0 AppImage tried various scenarios (config dir missing, no permissions, etc.), and I couldn't reproduce the bug or find any idea where it could be.

Do you have a repro with a debug version?

**Comment by sammdu** [comment]
@CrystallineCat I use the deb package if that helps. 
.deb on Ubuntu 18.04.

**Comment by vsivsi** [comment]
I have nteract v0.24.0 installed on three MacOS Catalina boxes. I see this bug on 1 out of the 3. On that machine I have uninstalled and reinstalled nteract and the issue persists. 

A strange behavior is that invoking menu: nteract>Quit causes the loading splash to go away, but _doesn't quit the app_.

Instead the menus remain operational. If I then go to e.g. File>New>node.js I get an error dialog with the dump below. I don't see this on any other machines:

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: Object has been destroyed
    at l._complete (/Applications/nteract.app/Contents/Resources/app.asar/lib/webpacked-main.js:44:31623)
    at l.t (/Applications/nteract.app/Contents/Resources/app.asar/lib/webpacked-main.js:11:10622)
    at l.__tryOrUnsub (/Applications/nteract.app/Contents/Resources/app.asar/lib/webpacked-main.js:11:10844)
    at l.complete (/Applications/nteract.app/Contents/Resources/app.asar/lib/webpacked-main.js:11:10759)
    at u._complete (/Applications/nteract.app/Contents/Resources/app.asar/lib/webpacked-main.js:11:9328)
    at u.complete (/Applications/nteract.app/Contents/Resources/app.asar/lib/webpacked-main.js:11:9130)
    at fr._complete (/Applications/nteract.app/Contents/Resources/app.asar/lib/webpacked-main.js:11:9328)
    at fr.complete (/Applications/nteract.app/Contents/Resources/app.asar/lib/webpacked-main.js:11:9130)
    at fr.notifyNext (/Applications/nteract.app/Contents/Resources/app.asar/lib/webpacked-main.js:11:298662)
    at i._next (/Applications/nteract.app/Contents/Resources/app.asar/lib/webpacked-main.js:11:164923)
```

Dismissing this dialog leads to a normal nteract document window that seems functional.

Hope this helps.

**Comment by NicholasWMRitchie** [comment]
Me too.  Windows 10 1909 18363.959.   Using Firefox as my primary browser.  
One Win10 box works, the other hangs on the splash screen.

**Comment by captainsafia** [comment]
> @captainsafia I looked through the code, and I downloaded the v.0.24.0 AppImage tried various scenarios (config dir missing, no permissions, etc.), and I couldn't reproduce the bug or find any idea where it could be.

> Do you have a repro with a debug version?

I was able to repro this on a Windows VM but haven't been able to track it down on either macOS machines I have. The issue doesn't reproduce reliably across all operating systems which is why we're seeing inconsistent reports from users.

This lack of a reliable reproduction can mean one of two things:

- There is indeed some common root cause (misconfigured Jupyter kernel, misconfigured configuration file, etc)
- The issue is unrelated to nteract and is caused by an external dependency (Electron in particular)

The exception @vsivsi shared above is interesting. Electron will through this exception if you attempt to access a value on an Electron window that has since been closed. The destroyed object in this case is an Observable object (indicated by the methods in the stack trace).

Interestingly, I didn't get a similar stack trace when I managed to track down the repro in the VM.

**Comment by clemwr** [comment]
I'm having the same issues on Windows 10 with 0.24.  I wonder if there is some conflict with other files like Jupyter that were installed with Anaconda

**Comment by gbrault** [comment]
This problem seems not solved: just tried to install nteract and run into it???

**Comment by clemwr** [comment]
Yeah, I just get the splash screen with the animation playing over and over.  It never gives an error or progresses to show menus.

**Comment by willingc** [comment]
@gbrault @clemwr The issue hasn't been resolved in the July nteract release. Sorry. 😞 One of the difficulties that we are having is reliably reproducing the issue across the different operating systems.

**Comment by willingc** [comment]
@captainsafia I've updated the milestone for an August 2020 release.

**Comment by willingc** [comment]
@captainsafia I'm pretty sure the error is in [this file](https://github.com/nteract/nteract/blame/main/applications/desktop/src/main/index.ts) and how we are handling startup, splash screen and timing.

**Comment by clemwr** [comment]
Here is additional information about the hanging splash screen in case it helps.  While the splash screen is up, I do not see nteract in the list of processes in my Task Manager.  Once I close the splash screen from its icon in the Task Bar, nteract then shows as a running process in Task Manager.  I can't switch to it, and all i can do is end it.  Some times it takes more than one attempt to end it.

**Comment by willingc** [comment]
Thanks @clemwr. Info like that is super helpful for narrowing down the issue.

**Comment by neolee** [comment]
Could we have a way to download older versions? The new 0.24 branch is a disaster for me, I just wanna use it as a stable and clean tool. Please let us download and use the oldie-goodie 0.23.x version. Thanks.

**Comment by willingc** [comment]
@neolee All releases are always available on GitHub. Here's a link to [0.23.3](https://github.com/nteract/nteract/releases/tag/v0.23.3).

Just a reminder that nteract is a volunteer open source project, not a business. We contribute to nteract and maintain these repos because we find it worthwhile and rewarding. While we wish that this issue was resolved, patience and collaboration will motivate us more than mentioning 0.24 as a disaster.

**Comment by neolee** [comment]
@willingc Thanks for the info! I haven't found that link myself.

**Comment by gbrault** [comment]
@willingc thanks for your help. I had no intent to point my finger to anybody. I hope you'll be able to recover from this issue soon.

**Comment by willingc** [comment]
You are welcome @gbrault @neolee. Thanks for the kind words. We're all good. I feel like we are getting closer to the cause which will hopefully result in a timely fix.

**Comment by willingc** [comment]
@captainsafia I did a `git bisect` this morning. This was the first commit that displayed errors when running `yarn build:desktop`:

```
➜ git bisect bad
a7e6cf562fd2b4e4e5781bba1f5c27e16fd5d2b9 is the first bad commit
commit a7e6cf562fd2b4e4e5781bba1f5c27e16fd5d2b9
Author: CrystallineCat <magda.kiesel@gmx.net>
Date:   Wed Jun 3 18:37:50 2020 +0200

    Centralize configuration as mythic-configuration

 .../desktop/__tests__/main/reducers.spec.ts        |  63 -------------
 .../__tests__/renderer/epics/config.spec.ts        |  18 ----
 .../src/common/commands/by-menu/preferences.ts     |  17 +++-
 applications/desktop/src/common/commands/types.ts  |   2 +
 applications/desktop/src/common/menu.ts            |  38 ++++++--
 applications/desktop/src/main/config-options.ts    |  18 ++++
 applications/desktop/src/main/index.ts             |  50 +++-------
 applications/desktop/src/main/menu.ts              |  74 ++-------------
 applications/desktop/src/main/reducers.ts          |  40 +-------
 applications/desktop/src/main/store.ts             |  38 +++++---
 applications/desktop/src/notebook/epics/config.ts  |  54 -----------
 applications/desktop/src/notebook/epics/index.ts   |  20 +---
 applications/desktop/src/notebook/global-events.ts |  11 +++
 applications/desktop/src/notebook/index.tsx        |   8 +-
 applications/desktop/src/notebook/store.ts         |   3 +-
 .../nteract_on_jupyter/app/store.ts                |   1 -
 applications/web/redux/store.ts                    |  10 +-
 package.json                                       |   1 +
 packages/actions/src/actionTypes/config.ts         |  24 -----
 packages/actions/src/index.ts                      |   1 -
 packages/editor/src/index.tsx                      |   9 +-
 packages/epics/__tests__/contents.spec.ts          |   6 +-
 packages/epics/package.json                        |   1 +
 packages/epics/src/contents.ts                     |  35 +++----
 packages/epics/tsconfig.json                       |   1 +
 packages/fixtures/src/index.ts                     |   8 +-
 packages/monaco-editor/src/index.tsx               |   6 --
 packages/mythic-configuration/README.md            |  93 +++++++++++++++++++
 .../__tests__/configuration.spec.ts                |  40 ++++++++
 packages/mythic-configuration/package.json         |  26 ++++++
 .../src/backends/filesystem.ts                     |  43 +++++++++
 packages/mythic-configuration/src/index.ts         |  99 ++++++++++++++++++++
 .../mythic-configuration/src/myths/load-config.ts  |   8 ++
 .../mythic-configuration/src/myths/merge-config.ts |  39 ++++++++
 .../mythic-configuration/src/myths/save-config.ts  |   9 ++
 .../src/myths/set-config-at-key.ts                 |  18 ++++
 .../src/myths/set-config-backend.ts                |  16 ++++
 .../src/myths/toggle-config-at-key.ts              |  22 +++++
 packages/mythic-configuration/src/package.ts       |  12 +++
 packages/mythic-configuration/src/types.ts         |  50 ++++++++++
 packages/mythic-configuration/tsconfig.json        |  11 +++
 packages/myths/src/store.ts                        |  19 ++--
 .../__tests__/decorators/themer.spec.tsx           |  25 -----
 packages/notebook-app-component/package.json       |   1 +
 .../src/decorators/themer/index.tsx                |  44 ---------
 .../decorators/undoable/undoable-cell-delete.tsx   |  14 ++-
 .../derived-components/themable-notifications.tsx  |   4 +-
 .../notebook-apps/draggable-with-cell-creator.tsx  |   6 +-
 packages/notebook-app-component/tsconfig.json      |   1 +
 packages/reducers/__tests__/config.spec.ts         |  24 -----
 packages/reducers/src/config.ts                    |  25 -----
 packages/reducers/src/index.ts                     |   3 +-
 packages/selectors/src/config.ts                   |  48 ----------
 packages/selectors/src/index.ts                    |   1 -
 .../__tests__/inputs/editor.spec.tsx               |   1 -
 packages/stateful-components/package.json          |   1 +
 .../src/cells/markdown-cell.tsx                    |  11 ++-
 packages/stateful-components/src/config-options.ts |  13 +++
 .../src/decorators/theme-from-config/index.tsx     |  32 +++++++
 packages/stateful-components/src/index.tsx         |   9 +-
 .../src/inputs/connected-editors/codemirror.tsx    | 101 ++++++++++++++++-----
 packages/stateful-components/src/inputs/editor.tsx |  20 ++--
 .../src/outputs/transform-media.tsx                |  12 +--
 packages/stateful-components/tsconfig.json         |   7 +-
 packages/tsconfig.json                             |   1 +
 packages/types/src/index.ts                        |   5 -
 packages/webpack-configurator/monorepo.js          |   5 +
 yarn.lock                                          |  39 ++++++++
 68 files changed, 884 insertions(+), 631 deletions(-)
 delete mode 100644 applications/desktop/__tests__/main/reducers.spec.ts
 delete mode 100644 applications/desktop/__tests__/renderer/epics/config.spec.ts
 create mode 100644 applications/desktop/src/main/config-options.ts
 delete mode 100644 applications/desktop/src/notebook/epics/config.ts
 delete mode 100644 packages/actions/src/actionTypes/config.ts
 create mode 100644 packages/mythic-configuration/README.md
 create mode 100644 packages/mythic-configuration/__tests__/configuration.spec.ts
 create mode 100644 packages/mythic-configuration/package.json
 create mode 100644 packages/mythic-configuration/src/backends/filesystem.ts
 create mode 100644 packages/mythic-configuration/src/index.ts
 create mode 100644 packages/mythic-configuration/src/myths/load-config.ts
 create mode 100644 packages/mythic-configuration/src/myths/merge-config.ts
 create mode 100644 packages/mythic-configuration/src/myths/save-config.ts
 create mode 100644 packages/mythic-configuration/src/myths/set-config-at-key.ts
 create mode 100644 packages/mythic-configuration/src/myths/set-config-backend.ts
 create mode 100644 packages/mythic-configuration/src/myths/toggle-config-at-key.ts
 create mode 100644 packages/mythic-configuration/src/package.ts
 create mode 100644 packages/mythic-configuration/src/types.ts
 create mode 100644 packages/mythic-configuration/tsconfig.json
 delete mode 100644 packages/notebook-app-component/__tests__/decorators/themer.spec.tsx
 delete mode 100644 packages/notebook-app-component/src/decorators/themer/index.tsx
 delete mode 100644 packages/reducers/__tests__/config.spec.ts
 delete mode 100644 packages/reducers/src/config.ts
 delete mode 100644 packages/selectors/src/config.ts
 create mode 100644 packages/stateful-components/src/config-options.ts
 create mode 100644 packages/stateful-components/src/decorators/theme-from-config/index.tsx
```

This is the first commit where I see the behavior happening with the splash screen. It doesn't necessarily mean that this commit has an error since it may be an error in an underlying package.

@captainsafia @CrystallineCat If you have any ideas on how to further troubleshoot, please pass them along.

**Comment by captainsafia** [comment]
Thanks @CrystallineCat for putting in a fix for this. The fix will ship in the August release of nteract.

In the meantime, try the workaround that is documented at https://github.com/nteract/nteract/issues/5254#issuecomment-671061120.
